name: CI-storage
on: 
  push: 
    branches:
      - main
jobs:
  kubernetes: 
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo apt-get install ./minikube_latest_amd64.deb
      - name: init
        run: minikube start --driver=docker
      - name: deploy-sc
        run: kubectl apply -f main/etc/kubernetes/manifests/sc-redis.yaml
      - name: deploy-pv
        run: kubectl apply -f main/etc/kubernetes/manifests/pv-redis.yaml
      - name: deploy-pvc
        run: kubectl apply -f main/etc/kubernetes/manifests/pvc-redis.yaml
      - name: deploy-po
        run: kubectl apply -f main/etc/kubernetes/manifests/po-redis.yaml
      - name: test
        run:  |
          while true
            do 
              sleep 10
              kubectl get all
              kubectl logs redis-po
              touch /tmp/redis/sebastian
              kubectl exec redis-po -- ls /data|grep sebastian&&break              
            done
